[package]
name = "libyang3-sys"
version = "0.6.0"
authors = ["Renato Westphal <renato@opensourcerouting.org>"]
description = "Raw FFI bindings for libyang3"
keywords = ["yang", "libyang"]
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/libyang3-sys"
categories = ["external-ffi-bindings"]

[dependencies]

[build-dependencies]
bindgen = { version = "0.68.0", optional = true }
cmake = { version = "0.1", optional = true }
pkg-config = "0.3.27"

[features]
# Use pre-generated FFI bindings
default = []
# Generate FFI bindings dynamically.
# For this to work libyang3 needs to be installed in the system.
bindgen = ["dep:bindgen"]
# Bundle libyang3 C files into a static archive linked to this crate.
# This removes the libyang3 dynamic link dependency.
bundled = ["dep:bindgen", "dep:cmake"]
